"""Addjust fk from trades to transactions

Revision ID: 84adc3b83ef8
Revises: 92e986094799
Create Date: 2024-12-01 14:28:56.031375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84adc3b83ef8'
down_revision: Union[str, None] = '92e986094799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('txn_id', sa.Integer(), nullable=True))
    op.drop_constraint('trades_txn_hash_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'transactions', ['txn_id'], ['id'])
    op.drop_column('trades', 'txn_hash')
    op.drop_index('ix_transactions_hash', table_name='transactions')
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    op.create_index('ix_transactions_hash', 'transactions', ['hash'], unique=False)
    op.add_column('trades', sa.Column('txn_hash', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key('trades_txn_hash_fkey', 'trades', 'wallets', ['txn_hash'], ['id'])
    op.drop_column('trades', 'txn_id')
    # ### end Alembic commands ###
