"""Change unique constraint on wallets table

Revision ID: ea2984fef5ae
Revises: 007d93667be4
Create Date: 2024-11-27 20:24:58.984881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea2984fef5ae'
down_revision: Union[str, None] = '007d93667be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pair_price_snapshot')
    op.drop_table('trade_pairs')
    op.drop_constraint('wallets_address_key', 'wallets', type_='unique')
    op.drop_constraint('wallets_name_key', 'wallets', type_='unique')
    op.create_unique_constraint('uq_address_chain_id', 'wallets', ['address', 'chain_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_address_chain_id', 'wallets', type_='unique')
    op.create_unique_constraint('wallets_name_key', 'wallets', ['name'])
    op.create_unique_constraint('wallets_address_key', 'wallets', ['address'])
    op.create_table('trade_pairs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker_buy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticker_sell', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('average_buy_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('available_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_trade_created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_trade_updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('trades_updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trade_pairs_pkey'),
    sa.UniqueConstraint('ticker_buy', 'ticker_sell', name='uix_ticker_buy_ticker_sell')
    )
    op.create_table('pair_price_snapshot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pair_price_snapshot_pkey'),
    sa.UniqueConstraint('symbol', name='pair_price_snapshot_symbol_key')
    )
    # ### end Alembic commands ###
